### PR TITLE
Scale speed

### PR DESCRIPTION
**Pull request by ArnoUUU**
added speed scaling

### CODE REVIEW

**Comment by ReeledWarrior14** [comment]
Change name of function "scaleSpeeds" to "oddSquare" because that is the method being employed. Also to make it consistent with our other repositories.

**Comment by LennyAbbas** [comment]
idk how but arnov managed to push broken code directly to main

**Comment by LennyAbbas** [comment]
scaleInput is a better name than oddSquare because it tells you what the method does. oddSquare doesn't make sense imo. It is inconsistent with other repositories but that just means we should change those ones as well.

**Review by LennyAbbas — APPROVED** [review]

**Comment by LennyAbbas** [comment]
we needed to merge that in right away so we don't have broken code on main. If you think oddSquare is a better name than scaleInput you can change it in another PR.

**Pull request merged**
